theme: jekyll-theme-minimal
title: David's website
logo: https://raw.githubusercontent.com/dagazrev/dagazrev.github.io/main/assets/_log.jpeg
description: Welcome to my personal site and have a look into the projects I've been working so far!